export default {
  SEARCH: {
    REQUEST: "REQUEST",
    RECEIVE: "RECEIVE"
  },

  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
  FILTER_FAVORITES: "FILTER_FAVORITES",

  MORE: {
    REQUEST: "REQUEST",
    RECEIVE: "RECEIVE"
  }

}
